src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\UtilisateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;
/**
 * @ORM\Entity(repositoryClass=UtilisateurRepository::class)
 */
class Utilisateur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("utilisateur")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("utilisateur")
     */
    private $login;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("utilisateur")
     *
     */
    private $password;

    /**
     * @ORM\Column(type="string")
     * @Groups("utilisateur")
     */
    private $role;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("utilisateur")
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("utilisateur")
     */
    private $prenom;

    /**
     * @ORM\Column(type="date")
     * @Groups("utilisateur")
     */
    private $date_naissance;

    /**
     * @ORM\Column(type="string", length=255)
     * * @Assert\NotBlank(message="Email est obligatoire")
     * ** @Assert\Email(message = "The email '{{ value }}' est invalide email.")
     * @Groups("utilisateur")
     */
    private $email;

    /**
     * @ORM\Column(type="integer")
     * @Groups("utilisateur")
     */
    private $num_tel;

    /**
     * @ORM\OneToMany(targetEntity=Destination::class, mappedBy="utilisateur", orphanRemoval=true)
     */
    private $destinations;

    /**
     * @ORM\OneToMany(targetEntity=Avis::class, mappedBy="utilisateur", orphanRemoval=true)
     */
    private $avis;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="utilisateur", orphanRemoval=true)
     */
    private $reservations;

    /**
     * @ORM\OneToMany(targetEntity=DemandeEvenement::class, mappedBy="utilisateur")
     */
    private $demandeEvenements;

    public function __construct()
    {
        $this->destinations = new ArrayCollection();
        $this->avis = new ArrayCollection();
        $this->reservations = new ArrayCollection();
        $this->demandeEvenements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLogin(): ?string
    {
        return $this->login;
    }

    public function setLogin(string $login): self
    {
        $this->login = $login;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getNumTel(): ?int
    {
        return $this->num_tel;
    }

    public function setNumTel(int $num_tel): self
    {
        $this->num_tel = $num_tel;

        return $this;
    }

    /**
     * @return Collection<int, Destination>
     */
    public function getDestinations(): Collection
    {
        return $this->destinations;
    }





    /**
     * @return Collection<int, Avis>
     */
    public function getAvis(): Collection
    {
        return $this->avis;
    }

    public function addAvi(Avis $avi): self
    {
        if (!$this->avis->contains($avi)) {
            $this->avis[] = $avi;
            $avi->setUtilisateur($this);
        }

        return $this;
    }

    public function removeAvi(Avis $avi): self
    {
        if ($this->avis->removeElement($avi)) {
            // set the owning side to null (unless already changed)
            if ($avi->getUtilisateur() === $this) {
                $avi->setUtilisateur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setUtilisateur($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getUtilisateur() === $this) {
                $reservation->setUtilisateur(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return  $this->login;
    }

    /**
     * @return Collection<int, DemandeEvenement>
     */
    public function getDemandeEvenements(): Collection
    {
        return $this->demandeEvenements;
    }

    public function addDemandeEvenement(DemandeEvenement $demandeEvenement): self
    {
        if (!$this->demandeEvenements->contains($demandeEvenement)) {
            $this->demandeEvenements[] = $demandeEvenement;
            $demandeEvenement->setUtilisateur($this);
        }

        return $this;
    }

    public function removeDemandeEvenement(DemandeEvenement $demandeEvenement): self
    {
        if ($this->demandeEvenements->removeElement($demandeEvenement)) {
            // set the owning side to null (unless already changed)
            if ($demandeEvenement->getUtilisateur() === $this) {
                $demandeEvenement->setUtilisateur(null);
            }
        }

        return $this;
    }
}

src/Form/DestinationType.php
<?php

namespace App\Form;

use App\Entity\Delegation;
use App\Entity\Destination;
use App\Entity\SousCategorie;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DestinationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('description', TextareaType::class, ['label' => "Description "])
            ->add('nom')
            ->add('image', FileType::class, array('data_class' => null))
            ->add('adresse')
            ->add('num_tel', TelType::class)
            ->add('email')
            ->add('souscategorie', EntityType::class, [
                'class' => SousCategorie::class,
                'choice_label' => 'libelle',
                'expanded' => false,
                'multiple' => false
            ])
            ->add('delegation', EntityType::class, [
                'class' => Delegation::class,
                'choice_label' => 'nom',
                'expanded' => false,
                'multiple' => false
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Destination::class,
        ]);
    }
}

src/Controller/DestinationController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Repository\DestinationRepository;
use App\Entity\Cout;
use App\Entity\Destination;
use App\Entity\destinationSearch;
use App\Entity\Gouvernorat;
use App\Entity\SousCategorie;
use App\Form\DestinationSearchType;
use App\Form\DestinationType;
use Doctrine\DBAL\Types\ArrayType;
use Knp\Component\Pager\PaginatorInterface;
use PhpParser\Node\Stmt\Catch_;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Validator\Constraints\Length;

class DestinationController extends Controller
{
    /**
     * @Route("/des", name="destination")
     */
    public function index(Request $request, DestinationRepository $repo, PaginatorInterface $paginator): Response
    {

        $search = new destinationSearch();
        $form = $this->createForm(DestinationSearchType::class, $search);
        $form->handleRequest($request);

        $liste_destination = $paginator->paginate($repo->findAllVisible($search), $request->query->getInt('page', 1), 4);

        $souscategories = $this->getDoctrine()->getRepository(SousCategorie::class)->findAll();
        $categorie = $this->getDoctrine()->getRepository(Categorie::class)->findAll();
        return $this->render('destination/destination_fornt.html.twig', [
            "souscat" => $categorie,
            "souscategories" => $souscategories,
            'liste_destination' => $liste_destination,
            'form' => $form->createView()


        ]);
    }
    /**
     * @Route("/dest/{id}", name="showcout")
     */
    public function couts($id)
    {
        $destination = $this->getDoctrine()->getRepository(Destination::class)->find($id);
        $cout = $this->getDoctrine()->getRepository(Cout::class)->findBy(array('destination' => $destination->getId()));

        return $this->render('destination/showcout.html.twig', [
            "destination" => $destination,
            "cout" => $cout,
        ]);
    }


    /**
     * @Route("/Destination/ajouter", name="create_destination")
     */
    public function create(Request $request): Response
    {

        $destination = new Destination();
        $form = $this->createForm(DestinationType::class, $destination);
        $form->add('save', SubmitType::class, ['label' => 'Enregistrer']);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $file = $destination->getImage();
            $fileName = md5(uniqid()) . '.' . $file->guessExtension();
            try {
                $file->move(
                    $this->getParameter('img_directory'),
                    $fileName
                );
            } catch (FileException $e) {
                // ... handle exception if something happens during file upload
            }

            $em = $this->getDoctrine()->getManager();
            $destination->setImage($fileName);
            $em->persist($destination);
            $em->flush();


            return $this->redirectToRoute('read_destination');
        } else {
            return $this->render('destination/adddestination.html.twig', [
                'controller_name' => 'DestinationController',
                'form' => $form->createView()
            ]);
        }
    }


    /**
     * @Route("/Destinations", name="read_destination")
     */
    public function Read(): Response
    {
        $liste_destination = $this->getDoctrine()->getRepository(Destination::class)
            ->findAll();
        return $this->render('destination/index.html.twig', [
            'controller_name' => 'CategorieController',
            'liste_destination' => $liste_destination

        ]);
    }


    /**
     * @Route("/Destination/supp/{id}", name="delete_destination")
     */
    public function delete($id)
    {

        $obj = $this->getDoctrine()->getRepository(Destination::class)->find($id);
        $em = $this->getDoctrine()->getManager();
        $em->remove($obj);
        $em->flush();
        return $this->redirectToRoute('read_destination');
    }


    /**
     * @Route("/Destination/modif/{id}", name="update_destination")
     */
    public function Update(Request $request, $id)
    { //chercher object a modifier

        $obj = $this->getDoctrine()->getRepository(Destination::class)->find($id);
        $form = $this->createForm(DestinationType::class, $obj);
        $form->add(
            'update',
            SubmitType::class,
            ['label' => 'Modifier']
        );
        $form->handleRequest($request);
        if (($form->isSubmitted()) && ($form->isValid())) {
            $em = $this->getDoctrine()->getManager();
            $em->flush();
            return $this->redirectToRoute('read_destination');
        } else {
            return $this->render(
                'destination/editdestination.html.twig',
                ['form' => $form->createView()]
            );
        }
    }

    /**
     * @Route("/destinationbycategorie/{id}", name="destination_essai")
     */
    public function destByCategorie(Request $request, DestinationRepository $repo, $id): Response
    {
        $search = new destinationSearch();
        $form = $this->createForm(DestinationSearchType::class, $search);
        $form->handleRequest($request);

        $liste_destination = $repo->findDestinationByString($id);
        $categorie = $this->getDoctrine()->getRepository(Categorie::class)->findAll();





        return $this->render('destination/destination.html.twig', [
            'controller_name' => 'DestinationController',
            "souscat" => $categorie,

            'liste_destination' => $liste_destination,
            'form' => $form->createView()

        ]);
    }

    /**
     * @Route("/destinationbycouts", name="prix")
     */
    public function destinationbycouts(): Response
    {
        return $this->render('destination/essai.html.twig', []);
    }

    /**
     * @Route("/destination/statistiques", name="statistiques")
     */
    public function statistiques(DestinationRepository $repo): Response
    {
        $Gouvernorats = $this->getDoctrine()->getRepository(Gouvernorat::class)->findAll();

        $datagouv = array();
        $labelgouv = array();
        foreach ($Gouvernorats as $cat) {
            array_push($datagouv, $repo->DestinationByGouvernoratstat($cat->getId()));
            array_push($labelgouv, $cat->getNom());
        }
        $souscategories = $this->getDoctrine()->getRepository(SousCategorie::class)->findAll();


        $data = array();
        $label = array();
        foreach ($souscategories as $cat) {
            array_push($data, $repo->destinationStat($cat->getId()));
            array_push($label, $cat->getLibelle());
        }
        return $this->render('destination/statistiques.html.twig', [
            'data' => json_encode($data),
            'label' => json_encode($label),
            'datagouv' => json_encode($datagouv),
            'labelgouv' => json_encode($labelgouv),


        ]);
    }
}

templates/destination/adddestination.html.twig
{% extends 'base.html.twig' %}





{% block stylesheets %}
<!-- Font Awesome -->
<link rel="stylesheet" href="{{ asset ('plugins/fontawesome-free/css/all.min.css')}}">
<!-- overlayScrollbars -->
<link rel="stylesheet" href="{{ asset ('plugins/overlayScrollbars/css/OverlayScrollbars.min.css')}}">
<!-- Theme style -->
<link rel="stylesheet" href="{{ asset ('dist/css/adminlte.min.css')}}">
{% endblock %}

{% block javascripts %}
<!-- jQuery -->
<script src="{{ asset ('plugins/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset ('plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- overlayScrollbars -->
<script src="{{ asset ('plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{ asset ('dist/js/adminlte.min.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset ('dist/js/demo.js')}}"></script>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

{% endblock %}

{% block body %}
  {{ form_start(form,{'attr': {'novalidate':'novalidate'}} ) }}

<div class="content" style="width:900px;height:500px;margin-left:30px">
  <div class="card card-secondary">
  <div class="card-header">
  <h3 class="card-title">Ajouter une Destination</h3>
 
  </div>
  <div class="modal-body">
          
    
        <div class="form-row">
          <div class="form-group col-md-4">
            {{ form_row(form.nom , {attr: {class: 'form-control',placeholder: 'Nom'}}) }}
          </div>
          <div class="form-group col-md-4">
            {{ form_row(form.email , {attr: {class: 'form-control',placeholder: 'email'}}) }}

          </div>
            <div class="form-group col-md-4">
                {{ form_row(form.num_tel , {attr: {class: 'form-control',placeholder: '71 171 717 '}}) }}

            </div>
            </div>
            
        <div class="form-row">
          <div class="form-group col-md-8">
            {{ form_row(form.description , {attr: {class: 'form-control',placeholder: 'bla bla bla bla bla..'}}) }}

          </div>
          <div class="form-group col-md-4">
            {{ form_row(form.souscategorie , {attr: {class: 'form-control',placeholder: '71 171 717 '}}) }}

          </div>
           </div>

          <div class="form-row">
            <div class="form-group col-md-6">
              {{ form_row(form.adresse , {attr: {class: 'form-control',placeholder: '14,rue,aghle tamimi'}}) }}

            </div>
            <div class="form-group col-md-4">
                {{ form_row(form.delegation , {attr: {class: 'form-control'}}) }}

            
       </div>
       <div class="form-row">
        <div class="form-group col-md-12">
          
                {{ form_row(form.image ) }}

         
       </div>
    
    
    </div>
   
    
    
      </div>
    
      <div class="modal-footer justify-content-between">
        <a type="button" href="{{path('read_destination')}}" class="btn btn-secondary ">Retour</a>

        {{ form_row(form.save , {attr: {class: 'btn btn-primary'}}) }}

      </div>
  </div>
  
  </div>
  </div>
 
  </section>
  
  </div>
  {{form_end(form)}}
{% endblock %}

templates/destination/destination.html.twig
{% extends 'destination/destination_fornt.html.twig' %}
{% block filtre  %}
{% endblock %}
 
              
              {% block destinations %}
              <section style="margin-left:10px">
              
                <div class="packages-content">
                  <div class="row">
                    {% for des in liste_destination  %}
                    {% if des.id == 3 %}
                    {% else %}
                      <div class="col-md-4 col-sm-6">
                      <div class="single-package-item">
                        <img src="{{ asset ('upload/image/'~ des.image)}}" alt="blog-img"  style="height:200px;width:200px;margin-left: 75px;">
                        <div class="single-package-item-txt">
                          <h3>{{des.nom}} <span class="pull-right">                                        {{ render(controller('App\\Controller\\DestinationController:couts',  { 'id': des.id })) }}
                          </span></h3>
                          <div style="margin-top:8px">{{des.description}} </div>
                            
                          <p>
                                           
                            {{des.description}}
                        </p>
                      
                       <br/>
                        <p><b>Adresse </b> <br/>
                       {{des.adresse}}, {{    des.delegation.nom}}  {{des.delegation.gouvernorat.nom}}</p>
                       <br/>
                       <p><b>Contact</b></p>

                    
                
                    <div class="row">
                      <div class="col-sm-2">
                       <p>{{des.email}}</p>
                      </div>
                      <div class="col-sm-2">
                       <p style="margin-left:160px">{{des.numTel}}</p> 
                        </div>
                        </div>
                        
                    
                        
                        </div><!--/.single-package-item-txt-->
                      </div><!--/.single-package-item-->
        
        
                    </div><!--/.col-->
                    {% endif %}
                    {% endfor %}
                  </div><!--/.row-->
                </div><!--/.packages-content-->
              </div><!--/.container-->

            </section><!--/.packages-->

         
            <!--packages end-->
            
            {% endblock  %}
           

        
         
             
               
              
              
          
          

templates/destination/destination_fornt.html.twig
{% extends 'front_destination.html.twig' %}

{% block body %}
    <!--Filtre-->
    <div style="margin-top:200px">
      <div class="container">
     
        <div class="row">
      
       
          
            <div class="col-md-12">
                <div class="single-travel-boxes">
                  <a type="button" href="{{path('destination')}}"  style="margin-top:12px;margin-left:12px  ">
                    <h4><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-return-left" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M14.5 1.5a.5.5 0 0 1 .5.5v4.8a2.5 2.5 0 0 1-2.5 2.5H2.707l3.347 3.346a.5.5 0 0 1-.708.708l-4.2-4.2a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 8.3H12.5A1.5 1.5 0 0 0 14 6.8V2a.5.5 0 0 1 .5-.5z"/>
                    </svg></h4>
                  </a>
                  
                    <div id="desc-tabs" class="desc-tabs">
                      
                        <ul class="nav nav-tabs" role="tablist" style="margin-left:400;margin-top:10px;;margin-bottom:10px">
                          
                            {% set id = null %}
                              {% for i in souscat %}
                              {% set id = i.id %}
                            <li class="active">
                                 <a href="{{path('destination_essai',{'id':i.id})}}" >
                                    
                                     <i class="fa fa-tree"></i>
                                     {{i.libelle}}
                                 </a>
                            </li>
                            {% endfor %}
                            
                           
                        </ul>
                        

              
               </div>
{% block filtre  %}
               <div  style="margin-left:50px;margin-top:20px">

                <button class="btn btn-secondary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                  <h4><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-filter" viewBox="0 0 16 16">
                    <path d="M6 10.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 0 1h-3a.5.5 0 0 1-.5-.5zm-2-3a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm-2-3a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5z"/>
                  </svg>Filtrer</h4>
                </button>
            </div>
               {% include 'destination/recherche.html.twig'%}
               {% endblock %}
              {% block destinations %}
              <section style="margin-left:10px">
              
                <div class="packages-content">
                  <div class="row">
                    {% for des in liste_destination  %}
                    {% if des.id == 3 %}
                    {% else %}
        
                    <div class="col-md-4 col-sm-6">
                      <div class="single-package-item">
                        <img src="{{ asset ('upload/image/'~ des.image)}}" alt="blog-img"  style="height:200px;width:200px;margin-left: 75px;">
                        <div class="single-package-item-txt">
                          <h3>{{des.nom}} <span class="pull-right">                                        {{ render(controller('App\\Controller\\DestinationController:couts',  { 'id': des.id })) }}
                          </span></h3>
                          <div style="margin-top:8px">{{des.description}} </div>
                            
                          <p>
                                           
                            {{des.description}}
                        </p>
                      
                       <br/>
                        <p><b>Adresse </b> <br/>
                       {{des.adresse}}, {{    des.delegation.nom}}  {{des.delegation.gouvernorat.nom}}</p>
                       <br/>
                       <p><b>Contact</b></p>

                    
                
                    <div class="row">
                      <div class="col-sm-2">
                       <p>{{des.email}}</p>
                      </div>
                      <div class="col-sm-2">
                       <p style="margin-left:160px">{{des.numTel}}</p> 
                        </div>
                        </div>
                        
                    
                        
                        </div><!--/.single-package-item-txt-->
                      </div><!--/.single-package-item-->
        
        
                    </div><!--/.col-->
                    {% endif %}
                    {% endfor %}

                  </div><!--/.row-->
                </div><!--/.packages-content-->
                <div style="margin-left:400px">{{knp_pagination_render(liste_destination)}}</div>

              </div><!--/.container-->
        
            </section><!--/.packages-->

         
            <!--packages end-->
{% endblock %}


{% endblock %}


              
          
          
           
            

templates/destination/index.html.twig
{% extends 'base.html.twig' %}


{% block body %}


<!-- /.row -->
<div class="card-body">
  <a class="btn btn-block btn-secondary "  href="{{path('create_destination')}}" style="margin-left:730px;width:200px">
    Ajouter une Destination
  </a>
  </div>
<div class="row fixed" style="margin-left:3%">
    <div class="col-16">
      <div class="card">
        <div class="card-header">
          <h3  >Liste des Destinations</h3>

          
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0" style="height: 360px;width:900px;">
          <table class="table table-head-fixed  table align-middle">
            <thead>
              <tr>
                <th>#</th>
                <th>Nom</th>
                <th>Email</th>
                <th>telephone</th>
                <th>Description</th>
                <th>Sous categorie</th>
                <th>Adresse</th>
                <th>Delegations</th>
                <th>Image</th>
                <th>editer</th>
                <th>supprimer</th>
              </tr>
            </thead>
           
            <tbody>
              {% for des in liste_destination %}
            <tr>
              <td>{{des.id}}</td>
              <td>{{des.nom}}</td>
              <td>{{des.email}}</td>
              <td>{{des.numTel}}</td>
              <td>{{des.description}} </td>
              <td>{{des.souscategorie.libelle}}</td>
              <td>{{des.adresse}}</td>
              <td>{{des.delegation.nom}}</td>
              <td><img src="{{ asset ('upload/image/'~ des.image)}}"  style="width:40px;height:40px"/></td>
              ><td><a href="{{path('update_destination',{'id':des.id})}}" class="nav-link" style="color:rgb(224, 110, 3);">
                  <i class="nav-icon fas fa-edit"></i></a></td>
              <td><a href="{{path('delete_destination',{'id':des.id})}}" class="nav-link " style="color:rgb(190, 18, 18);">
                  <i class="nav-icon fas fa-trash"></i></a></td>
              
             
            </tr>
            {% endfor %}
           
              
          </tbody>

          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
  </div>
  
  
  
{% endblock %}

templates/destination/recherche.html.twig
{% block filtre %}

  
{{form_start(form)}}
<div class="collapse" id="collapseExample">

<section  class="travel-box" style="margin-top:130px">

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="single-travel-boxes">
          <div id="desc-tabs" class="desc-tabs">
            <div class="tab-content">
               <div role="tabpanel" class="tab-pane active fade in" id="tours">
                 <div class="tab-para">
                   
                   <div class="form-row">
                     <div class="form-group col-md-4">
                          {{ form_row(form.name , {attr: {class: 'form-control'}}) }}
                     </div>
                     <div class="form-group col-md-4">
                          {{ form_row(form.prix , {attr: {class: 'form-control'}}) }}
                          
                     </div>
                     <div class="form-group col-md-4">
                         {{ form_row(form.gouvernorat , {attr: {class: 'form-control'}}) }}
                     </div>
                    </div>
                  

              <div class="row">
                
                <div class="clo-sm-7">
                  <div class="about-btn    pull-right">
                    <button  class="about-view travel-btn">
                      Filtrer	
                    </button><!--/.travel-btn-->
                  </div><!--/.about-btn-->
                </div><!--/.col-->

              </div><!--/.row-->

            </div><!--/.tab-para-->

          </div><!--/.tabpannel-->

         
   
        </div><!--/.tab content-->
      </div><!--/.desc-tabs-->
        </div><!--/.single-travel-box-->
      </div><!--/.col-->
    </div><!--/.row-->
  </div><!--/.container-->

</section><!--/.travel-box-->
<!--travel-box end--> 
</div>
{{form_end(form)}}

{% endblock %}

templates/destination/showcout.html.twig
  
  <span  class="smooth-menu" >
                                    
                                
                                
    <div class="d-flex">
      <div class="dropup">
        <button class=" about-view packages-btn"  id="deroulanta" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"  style="background-color: rgb(207, 209, 211);border-color: rgb(200, 208, 214);">Tarif</button>
        <div class="dropdown-menu" aria-labelledby="deroulanta">
        
          {% for cout in cout %}
          <p class="dropdown-item" style="margin-left:20px;">{{cout.coutcategorie.libelle}}<span style="margin-left:20px;" >   {{cout.prix}} </span>DT</p><br/>
          
          {% endfor %}
        </div>
      </div>
    </div>
  </span>